// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwszqmnbgvwklgsyfdrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3c3pxbW5iZ3Z3a2xnc3lmZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTY3NTYsImV4cCI6MjA3MDIzMjc1Nn0.QfXudjZzy05DJ053NSfJb3AYcBz4QOdRkOj2pjoymnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});